### ISSUE TITLE
Line response should contain at least the required fields + ID

### ISSUE THREAD

**Issue by radualexiulian** [Outsmart-OOH/ooh_open_direct#10]
In this example the only required fields are Id and Name - Name is not mandatory when creating the resource - maybe it should also be required.
https://github.com/Outsmart-OOH/ooh_open_direct/blob/master/schema/v1/uris/lines/lines_response.json

**Comment by knittingmedia** [comment]
Added Name to 'line request' schema here:   https://raw.githubusercontent.com/Outsmart-OOH/ooh_open_direct/master/schema/v1/uris/lines/lines_request.json
