### ISSUE TITLE
When and who should supply the data in the OOHProviderData

### ISSUE THREAD

**Issue by radualexiulian** [Outsmart-OOH/ooh_open_direct#11]
Can we have some details around _who_ and _when_ should the fields from OOHProviderData object be supplied? Should the buyer send the SOR in a specific moment in time (after option, after is created, after book etc) or it can differ from seller to seller?
As an example, in our current system, we can offer the PoNumber only before the first book happens on an Order - using a PATCH command

**Comment by knittingmedia** [comment]
Order OOHProviderData is generated by the buyer when the order is created. Line OOHProviderData created by the buyer when Line is created. Both can be updated by the Buyer via a change request.

If the Seller has their own commercial rules that requires a Order and/or Line to have a Purchase Order Number attached to make a booking, the Sell Side can send an explicit error response if the buyer tries to book without a Purchase Order Number.

It is proposed that a Seller should publish such commercial rules in a text file accessible via the Collection Objects facility e.g. call URI / collectionobjects/businessrules

This information has been added to the main document

**Comment by knittingmedia** [comment]
ACTION: Close?
