### ISSUE TITLE
No fields are required when creating an Organization

### ISSUE THREAD

**Issue by radualexiulian** [Outsmart-OOH/ooh_open_direct#12]
https://github.com/Outsmart-OOH/ooh_open_direct/blob/master/schema/v1/uris/organizations/organizations_request.json

**Comment by knittingmedia** [comment]
At the moment the Sell Side creates all Organizations, this is not a schema nor API function that will be used by the Buy Side. It is up to the Sell Side to populate the Organization data according to the schema guideline. If the Organization schema is opened to the Buy Side, it is advised that the schema should then identify required fields to match Sell Side expectations.

Main Document updated with this text (Section 2.6)
