### ISSUE TITLE
Who will populate the field AdvertiserBrands when creating a new Orga?

### ISSUE THREAD

**Issue by radualexiulian** [Outsmart-OOH/ooh_open_direct#13]
This is a little confusing:
In order to create an _Organization_,the are 2 possible cases if _AdvertiserBrands_ is 
1. Mandatory => how can you supply the _AdvertiserBrands_ if this resource can't be created by the caller (no endpoints exposed for this)? Even if the buyer can create it, it's a circular dependency since the _AdvertiserBrand_ resource requires the prior presence of the _Organization_ resource. 
2. Optional => How will the buyer know what brands can be associated with the newly created _Organization_?

**Comment by knittingmedia** [comment]
When creating an Organization, AdvertiserBrands cant be added. AdvertiserBrands are created after an organization comes into being. 

The AdvertiserBrand IDs are exposed by the Seller in the Collection Object URI /advertiserbrands/advertiserbrands?$filter
