### ISSUE TITLE
AdvertiserBrands field description must be corrected

### ISSUE THREAD

**Issue by radualexiulian** [Outsmart-OOH/ooh_open_direct#14]
In section _2.6 Organisation_ (https://github.com/Outsmart-OOH/ooh_open_direct/blob/master/docs/v1-1/OpenDirect_OOH_1-5-1_v1-1.md#26-organisation) the _AdvertiserBrands_ must be a list of Brand objects, and not a list of Brand ID's as per description.

**Comment by knittingmedia** [comment]
Table updated
