### ISSUE TITLE
How can we infer what is required for UPDATE based on the URI's schema?

### ISSUE THREAD

**Issue by radualexiulian** [Outsmart-OOH/ooh_open_direct#15]
The URI's schema should probably also contain the required fields when updating a resource. There could be cases where a field can't be modified once created (for ex, in the old spec, the ProductId from the Line was required at ADD, but readonly at UPDATE)

**Comment by knittingmedia** [comment]
ACTION: Schema for each URI action? e.g. 'post, patch, get' call by 'request' is needed. Double check that all responses are standard.
See matrix [here](https://docs.google.com/spreadsheets/d/1urU3J-RF5Pd7kG4Z_9fJjME9G67qYgKWrjVvhAi8gzU/edit?usp=sharing) (Markdown Examples Index tab)

**Comment by knittingmedia** [comment]
Please see the most up to date document (v1_2) and schema and resubmit issue if still applicable
