### ISSUE TITLE
<DataSource> SPACE, linked_asset_id

### ISSUE THREAD

**Issue by knittingmedia** [Outsmart-OOH/ooh_open_direct#22]
From Luka Djukic:
Inventory OOHbject - targeting by 'Linked Asset Id'
In Inventory,Frames,SPACE could we add 'linked_asset_id' as a possible target? Some of Ocean's locations are represented as linked assets on SPACE, so we would need to allow buyers to target by Linked Asset Id.

**Comment by knittingmedia** [comment]
Yes! as SPACE is a <DataSource> this is driven by SPACE descriptions so is allowed
ACTION: update Inventory OOHbject table example in document

**Comment by ldjukic** [comment]
Thanks Tim.
Could we also add a JSON example of availability check where the buyer targets both a Frame and a Linked Asset?

**Comment by knittingmedia** [comment]
Added to Inventory OOHbject table (4.14) community example needed
