### ISSUE TITLE
mistake in the required fields of the single product response.

### ISSUE THREAD

**Issue by arvsr1988** [Outsmart-OOH/ooh_open_direct#26]
I think there is a mistake in the required fields of the single product response.
 
the GET /products collection response has the following required fields in the schema `[  "ActiveDate", "Id", "Name", "TargetTypes" ]`
the GET /product response has the following required fields `"required": ["Id", "Name", "TargetTypes", "AvailsGroupBy"]`

I think the AvailsGroupBy in the single product response should be ActiveDate.

**Comment by knittingmedia** [comment]
Please see the most up to date document (v1_2) and resubmit issue if still applicable
