### ISSUE TITLE
ProductAvails - StartDate and EndDate

### ISSUE THREAD

**Issue by ldjukic** [Outsmart-OOH/ooh_open_direct#29]
According to the spec and the JSON schemas, StartDate and EndDate are present in ProductAvailsSearch but not in ProductAvails (see sections [3.5](https://github.com/Outsmart-OOH/ooh_open_direct/blob/master/docs/v1-1/OpenDirect_OOH_1-5-1_v1-1.md#35-productavailssearch) and [3.4](https://github.com/Outsmart-OOH/ooh_open_direct/blob/master/docs/v1-1/OpenDirect_OOH_1-5-1_v1-1.md#34-productavails) respectively).

Shouldn't the StartDate and EndDate specified in the request (i.e. in ProductAvailsSearch) be also present in the response (i.e. in ProductAvails)? Otherwise how do we know in the response which dates are being targeted?

**Comment by knittingmedia** [comment]
Agreed, to action in table and examples
