### ISSUE TITLE
Account - can ThirdPartyId be updated? 

### ISSUE THREAD

**Issue by ldjukic** [Outsmart-OOH/ooh_open_direct#31]
When updating an Account (PATCH /accounts/{id}), can the buyer change the ThirdPartyId to point to an other Organization? Or should the 'ThirdPartyId' field be uneditable?

**Comment by knittingmedia** [comment]
It's advised that a buyer can't change the id, buyerid, brandid but could change the name? Accounts should not be deletable by the buy side too. (check disable status)

**Comment by ldjukic** [comment]
Thanks Tim. Fine by me.
If this has been officially confirmed, I think we can close the issue.
