### ISSUE TITLE
ProductAvails - Partial availability response

### ISSUE THREAD

**Issue by ldjukic** [Outsmart-OOH/ooh_open_direct#32]
I would need some clarification on the information sent in the response of an availability search when the targeted inventory is partially available.

### Example

**Request**

I'm targeting a share of time of 25% on [08-10] on Monday 19th April 2021 for Frame '2000109869'.

The request will look something like this:
<pre>{
    "AccountId": "b406f971-0d26-4c60-bd68-817cb34cb8b7",
    "ProductIds": ["f8235bf7-02a5-4cf6-995b-b5f9ff5d9335"],
    "StartDate": "2021-04-19T00:00:00.000+01:00",
    "EndDate": "2021-04-20T00:00:00.000+01:00",
    "Targeting": [
        {
            "Name": "Inventory",
            "Type": "Frames",
            "DataSource": "Space",
            "Target": "frame_id",
            "TargetValues": [ "2000109869" ]
        },
        {
            "Name": "Delivery",
            "Type": "Frames",
            "DataSource": "Time",
            "Target": "Hours",
            "TargetValues": [ "8", "9" ]
        },
        {
            "Name": "Delivery",
            "Type": "Frames",
            "DataSource": "ShareOfDisplay",
            "Target": "ShareOfTime",
            "TargetValues": [ "25" ]
        }
    ],
    "AvailabilityFields": [
        {
            "Name": "Inventory",
            "Type": "Frames",
            "DataSource": "Space",
            "Target": "frame_id"
        },
        {
            "Name": "Delivery",
            "Type": "Frames",
            "DataSource": "Time",
            "Target": "Hours"
        },
        {
            "Name": "Delivery",
            "Type": "Frames",
            "DataSource": "ShareOfDisplay",
            "Target": "ShareOfTime"
        }
    ],
    "Grouping": [
        {
            "Name": "Inventory",
            "Type": "Frames",
            "DataSource": "Space",
            "Target": "frame_id"
        }
    ]
}</pre>

**Response**

Let's assume that [08-09] is available, but that there is no space left on [09-10] because all of it is booked by other campaigns.

What should the response look like? More specifically, should the Frame be flagged as 'partially available', with information provided only on the part that is available?
I.e. something like this:
<pre>
{
  "ProductAvails" : [ {
    "ProductId" : "f8235bf7-02a5-4cf6-995b-b5f9ff5d9335",
    "Currency" : "GBP",
    "Price" : 1000.0,
    "StartDate" : "2021-04-19T00:00:00.000+01:00",
    "EndDate" : "2021-04-20T00:00:00.000+01:00",
    "Availability" : [ {
      "Status" : "Partially Available",
      "Reason" : "Booked",
      "Targeting" : [ {
        "Name" : "Inventory",
        "Type" : "Frames",
        "DataSource" : "Space",
        "Target" : "frame_id",
        "TargetValues" : [ "2000109869" ]
      }, {
        "Name" : "Delivery",
        "Type" : "Frames",
        "DataSource" : "Time",
        "Target" : "Hours",
        "TargetValues" : [ "8" ]
      }, {
        "Name" : "Delivery",
        "Type" : "Frames",
        "DataSource" : "ShareOfDisplay",
        "Target" : "ShareOfTime",
        "TargetValues" : [ "25" ]
      } ] 
    } ]
  } ]
}
</pre>

Or should the part that is unavailable (i.e. [09-10]) appear under 'Unavailable' so that the response has the same scope (in terms of targeting) as the request?

**Comment by knittingmedia** [comment]
If the availability fields response is requested at campaign or week level, the response can only be quantified as 'partially available' in terms of a campaign/week (as there is no hour field to quantify this)
If the response is requested with availability fields at hour level, the response can be given as available and unavailable at hour level.
TBC

**Comment by ldjukic** [comment]
Thanks Tim. It's fine for me.
Has this been officially confirmed?
