### ISSUE TITLE
ProductAvails - Duplication

### ISSUE THREAD

**Issue by ldjukic** [Outsmart-OOH/ooh_open_direct#33]
In the context of an availability search, if the request contains duplicate values (e.g. if the same frame_id is listed multiple times), should the response be an error message or an 'Unavailable' status with a 'Duplication' reason?

Example of request:
<pre>{
    "AccountId": "b406f971-0d26-4c60-bd68-817cb34cb8b7",
    "ProductIds": ["f8235bf7-02a5-4cf6-995b-b5f9ff5d9335"],
    "StartDate": "2021-04-19T00:00:00.000+01:00",
    "EndDate": "2021-04-20T00:00:00.000+01:00",
    "Targeting": [
        {
            "Name": "Inventory",
            "Type": "Frames",
            "DataSource": "Space",
            "Target": "frame_id",
            "TargetValues": [ "2000109869", "2000109869" ]
        }
    ]
}</pre>

**Comment by knittingmedia** [comment]
Recommended to return an error message
e.g  "Name": "Inventory",
            "Type": "Frames",
            "DataSource": "Space",
            "Target": "frame_id",
duplicate target values"

(tidy up)

**Comment by ldjukic** [comment]
Thanks Tim. Fine by me.
If this has been officially confirmed, I think we can close the issue.
