### ISSUE TITLE
Success reponse message

### ISSUE THREAD

**Issue by ldjukic** [Outsmart-OOH/ooh_open_direct#34]
In most cases, when a request succeeds, the response consists of the underlying resource (e.g. when creating a Line the response presents the properties of that Line).

However in the case of a DELETE (e.g. when deleting a Line), the underlying resource doesn't exist anymore if the request is succesful.

What should the response be in that case?

Should it be a message such as:
<pre>{
  "Message" : "Line successfully deleted"
}</pre>
?

**Comment by knittingmedia** [comment]
Return http 200 successful response
