### ISSUE TITLE
Line - productAvails_object or productAvails_Availability_object?

### ISSUE THREAD

**Issue by ldjukic** [Outsmart-OOH/ooh_open_direct#38]
The Line resource (line_object.json) uses a ProductAvails object (productAvails_object.json) to return detailed availability information in the event of the line reserve/booking request failing.

Wouldn't it be more adapted to use a ProductAvails_Availability object (productAvails_Availability_object.json) instead, since the other properties of the ProductAvails object are already specified at the Line level?

**Comment by knittingmedia** [comment]
Hi Luka, The logic was that as you always run a productAvails_Availability call before you create a booking line, the booking line would be expected to succeed, hence the use of the lighter productAvails_object (which does not have the Avails/Partially Avails and Unavails in it) when you create the booking line.

**Comment by knittingmedia** [comment]
If the line reserve/booking request fails this information is included in the Error Message (there is an Availability Object in the Error message in V1_2)
