### ISSUE TITLE
Frame ID type mismatch

### ISSUE THREAD

**Issue by spavett** [Outsmart-OOH/ooh_open_direct#5]
Is there a type mismatch for frame IDs between different request/response examples? Given that we don't know if a data source will use numbers or strings can we force all matching to be strings? 

[https://github.com/Outsmart-OOH/ooh_open_direct/blob/master/examples/OOHpenDirect_1-5-1_v-1/POST_avails_(and)_request_001.json](https://github.com/Outsmart-OOH/ooh_open_direct/blob/master/examples/OOHpenDirect_1-5-1_v-1/POST_avails_(and)_request_001.json)

```json
{
    "Name": "Inventory",
    "Type": "Frames",
    "DataSource": "Space",
    "Target": "frame_id",
    "TargetValues": [
        1234931339,
        1235190735
    ]
}
```

[https://github.com/Outsmart-OOH/ooh_open_direct/blob/master/examples/OOHpenDirect_1-5-1_v-1/POST_avails_(and)_reponse.json](https://github.com/Outsmart-OOH/ooh_open_direct/blob/master/examples/OOHpenDirect_1-5-1_v-1/POST_avails_(and)_reponse.json)

contains 
```json
{
    "Name": "Inventory",
    "Type": "Frames",
    "DataSource": "Space",
    "Target": "frame_id",
    "TargetValues": ["1234931339"]
 }
```

[https://github.com/Outsmart-OOH/ooh_open_direct/blob/master/examples/OOHpenDirect_1-5-1_v-1/POST_avails_(frames)_request.json](https://github.com/Outsmart-OOH/ooh_open_direct/blob/master/examples/OOHpenDirect_1-5-1_v-1/POST_avails_(frames)_request.json)

```json
{
    "Name": "Inventory",
    "Type": "Frames",
    "DataSource": "Space",
    "Target": "frame_id",
    "TargetValues": [
        1234931339,
        1235190735,
        1234931338,
        1235191547
    ]
}
```

[https://github.com/Outsmart-OOH/ooh_open_direct/blob/master/examples/OOHpenDirect_1-5-1_v-1/POST_avails_(frames)_response.json](https://github.com/Outsmart-OOH/ooh_open_direct/blob/master/examples/OOHpenDirect_1-5-1_v-1/POST_avails_(frames)_response.json)

```json
{
    "Name": "Inventory",
    "Type": "Frames",
    "DataSource": "Space",
    "Target": "frame_id",
    "TargetValues": [
        1234931339
    ]
}

**Comment by knittingmedia** [comment]
TargetValues changed to a "String" and all examples updated
