### ISSUE TITLE
Most of the schema's are missing important constraints details

### ISSUE THREAD

**Issue by radualexiulian** [Outsmart-OOH/ooh_open_direct#9]
Like min, max etc

**Comment by knittingmedia** [comment]
Action: update schemas, see line_id_string, organization_id_string for consistent use REGULAR EXPRESSION

**Comment by knittingmedia** [comment]
Summary of common object attributes compiled [here](https://docs.google.com/spreadsheets/d/1urU3J-RF5Pd7kG4Z_9fJjME9G67qYgKWrjVvhAi8gzU/edit?usp=sharing) (UniqueAttributesAnalysis tab)

ACTION: Create 'REGULAR EXPRESSION schemas' for attributes used in more than one place. Ensure other attributes have all min/max/length properties updated. Be careful not to mix attributes that relate to unique object functions (e.g. Name) or depart from the OpenDirect standard.

**Comment by knittingmedia** [comment]
Fixed with introduction of new OOHbject schemas
